Qa8 1455
EAGauss/MLH-21801 pull request #25
Opened 2021-04-06 17:36 UTC by oksanakirieieva

added TC-070

2021-04-06 22:18 UTC, isenkovska approved these changes
looks good

2021-04-07 07:24 UTC, EAGauss requested changes
You have deleted the "seventyOneSymbols" and "my" from the testData.js which is critical because my tests are failing now, so restore them, please.
It's better to run a full regression before you make a pull request. 
And a minor comment - don't forget to remove trailing commas. For example, you shouldn't have added the comma at the end of the "age" object in testData.js

2021-04-07 07:30 UTC, o-akhadova requested changes
I agree with Emil, also you can delete 44 line from TC-71, because it's not necessary there

2021-04-07 14:41 UTC, Slyvochka approved these changes

2021-04-07 14:41 UTC, ivansh83 approved these changes

2021-04-07 14:42 UTC, EAGauss approved these changes

2021-04-07 14:43 UTC, merged