Qa8 1481
EAGauss/MLH-21801 pull request #33
Opened 2021-04-07 17:42 UTC by natdem

Add TC-066

2021-04-07 23:12 UTC, isenkovska requested changes

2021-04-07 23:12 UTC, isenkovska commented on data/expected.json
> +  "agePlaceholder":"Hero's age"
can you please move agePlacholder into row 12, just under age label;

2021-04-07 23:12 UTC, isenkovska commented on data/selectors.js
> +    "tryAgain": ".btn-primary",
could you please delete comma from  the row 30, after "tryAgain": ".btn-primary",

2021-04-07 23:34 UTC, natdem commented on data/expected.json
> +  "agePlaceholder":"Hero's age"
All fixed

2021-04-07 23:35 UTC, natdem commented on data/selectors.js
> +    "tryAgain": ".btn-primary",
All fixed

2021-04-07 23:36 UTC, isenkovska approved these changes
looks good

2021-04-08 04:46 UTC, ivansh83 approved these changes
Good job!

2021-04-08 04:47 UTC, merged